version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker info
      - run: docker build --rm=false -t test1 .
      - run: docker run --name dockertest -it  test1
