version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker info
      - run: docker build --rm=false -t test1 .
      - run: docker run --name dockertest -it  test1
      - run: echo $CIRCLE_ARTIFACTS
      - run: docker cp dockertest:/root/src/build /tmp/dockertest
      - run: mkdir /tmp/pub_release
      - run: cp /tmp/dockertest/*.gta /tmp/pub_release
      - run: cp /tmp/dockertest/Makefile /tmp/pub_release
      - run: tar czvf /tmp/dockertest_release_pub.tar.gz -C /tmp/pub_release/ .

      - store_artifacts:
          path: /tmp